### ISSUE TITLE
Does not open mail compose window in pre-release versions of Firefox (e.g. Nightly)

### ISSUE THREAD

**Issue by steveray100** [MikkCZ/send-link-from-context-menu#13] opened 2020-07-06 02:08 UTC
in Firefox 78, when I try to use the context menu item. it no longer works. It used to open Thunderbird with a new message with the link in the message. PLEASE PLEASE FIX! This is my most useful and favorite extension!

**Comment by liar666** [comment] 2020-07-07 15:54
Same problem here :[
For those looking for a (temp?) work-around, it seems that the following extension has similar functionality:
https://addons.mozilla.org/en-US/firefox/addon/send-to-mail

**Comment by MikkCZ** [comment] 2020-07-07 17:49
Thank you for the report. I've been notified about this issue via e-mail too, however it's shortly before me going offline for two weeks. I will be able to debug and adjust the add-on for new Firefox version in the second half of July. I sorry for such delay.

**Comment by MikkCZ** [comment] 2020-07-07 17:55
Just in case you are a developer and want to speed up the fix, feel free to submit a PR any time. I will be happy to review it and even discuss changing the add-on ownership. It's available for adoption.

**Comment by MikkCZ** [comment] 2020-07-17 11:43
I found out that it's probably unintended regression in Firefox. I filed [bug 1653541](https://bugzilla.mozilla.org/show_bug.cgi?id=1653541) and wait a while if there is any response and ETA for a fix. Based on that I will either wait for next Firefox release with a fix, or start working on a temporary workaround.

**Comment by MikkCZ** [comment] 2020-07-17 14:07
There is a workaround on Firefox side, which is to flip `security.allow_disjointed_external_uri_loads` to `true`. Mozilla did that for Firefox 78 and now for 79 too. I will watch the situation for future update, but it should work in the current and closest upcoming release.

**Comment by MikkCZ** [comment] 2020-07-21 14:37
Resolved by Mozilla for future versions in the bug mentioned above. The current versions have been hotfixed by reverting the change in configuration.

**Closed as completed by MikkCZ** 2020-07-21 14:37 UTC
Labels: bug
